CREATE TABLE characters (
        id SERIAL PRIMARY KEY,
        user_id INT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
        faction_id INT NOT NULL REFERENCES factions(id),
        class_id INT NOT NULL REFERENCES classes(id),
        name VARCHAR(32) NOT NULL UNIQUE,
        role VARCHAR(16) NOT NULL DEFAULT 'dd',
        level SMALLINT NOT NULL DEFAULT 1,
        experience INT NOT NULL DEFAULT 0,
        avatar VARCHAR(255),
        hp INT NOT NULL DEFAULT 100,
        mp INT NOT NULL DEFAULT 100,
        hp_current INT NOT NULL DEFAULT 100,
        mp_current INT NOT NULL DEFAULT 100,
        mastery INT NOT NULL DEFAULT 10,
        endurance INT NOT NULL DEFAULT 10,
        power INT NOT NULL DEFAULT 10,
        accuracy INT NOT NULL DEFAULT 0,
        alacrity INT NOT NULL DEFAULT 0,
        critical INT NOT NULL DEFAULT 0,
        defense INT NOT NULL DEFAULT 0,
        shield INT NOT NULL DEFAULT 0,
        absorption INT NOT NULL DEFAULT 0,
        created_at TIMESTAMP NOT NULL DEFAULT NOW(),
        updated_at TIMESTAMP NOT NULL DEFAULT NOW()
);